### ISSUE TITLE
Is there existing code to cold-start items?

### ISSUE THREAD

**Issue by ThomasAger** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#11]
Hi, I was wondering how some of the algorithms performed with cold-start items, particularly ItemKNNCBF and ItemKNNCBFCF. Is there some existing code to do this? I saw on the SpectralCF work there was one for increasing sparsity of users.

**Comment by ThomasAger** [comment]
I tried writing my own splitter that separated 20% of cold item interactions, but when running it all of the scores came out zero. I'm not sure why, but I likely missed something.

```
def split_train_validation_cold_start_items(URM_train, train_percentage=0.2):
    from Data_manager.IncrementalSparseMatrix import IncrementalSparseMatrix

    num_users, num_items = URM_train.shape

    URM_train_builder = IncrementalSparseMatrix(n_rows=num_users, n_cols=num_items)
    URM_validation_builder = IncrementalSparseMatrix(n_rows=num_users, n_cols=num_items)

    # Select 20% of items

    URM_train = sps.csr_matrix(URM_train)

    train_mask = URM_train.indices < int(URM_train.shape[1] * train_percentage)
    # Add one of each item to the train set
    validation_mask = np.logical_not(train_mask)

    URM_train = sps.coo_matrix(URM_train)

    URM_train_builder.add_data_lists(URM_train.row[train_mask], URM_train.col[train_mask], URM_train.data[train_mask])

    URM_validation_builder.add_data_lists(URM_train.row[validation_mask], URM_train.col[validation_mask], URM_train.data[validation_mask])

    URM_train = URM_train_builder.get_SparseMatrix()
    URM_validation = URM_validation_builder.get_SparseMatrix()


    return URM_train, URM_validation
```

**Comment by MaurizioFD** [comment]
Hi,

I don't think I ran experiments for cold items...

You can see examples of ItemKNNCBF and ItemKNNCBFCF used in CollaborativeVAE and MCREc, there you will also find some feature data to use. 

Regarding your splitter, you don't need to use the IncrementalSparseMatrix in this case, you can just instantiate a new sparse matrix directly. 
Also, you are creating the train_mask based on the indices data, while then you are using it on the coo format, you should not mix the two because the ordering in the internal data will be different and you will probably obtain inconsistent results.

You should do something like
train_mask = URM_train.col < int(URM_train.shape[1] * train_percentage)

Lastly, If you plan on running experimental evaluations on cold items, I would suggest you randomize them instead of selecting the first/last ones. Their index depends on the ID in the original data, which may be a function of something like "time" and that could hide the fact that you are sampling a specific data distribution (older so likely rather popular items or newer so likely less popular ones) which could be inconsistent across datasets.

**Comment by ThomasAger** [comment]
Thanks :) I'll keep trying!
