### ISSUE TITLE
Question about SLIMElasticNet

### ISSUE THREAD

**Issue by JaireYu** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#13]
Hello, I am building a recsys recently and learning something from your code.

I notice that your code about SLIMElasticNet only reserves Top-K element in each column of W-matrix and set other element to zero. I have trouble understanding this, because I don't find any clue in the [paper](http://glaros.dtc.umn.edu/gkhome/fetch/papers/SLIM2011icdm.pdf) suggesting we should do this. 

Could you please help me solve the problem? Thank you very much!

**Comment by MaurizioFD** [comment]
Hello,

Consider that the version of SLIM we use is a variant of the one originally proposed by Ning and Karypis that you have mentioned. In practice, the training procedure is only slightly different and the similarity is learned one item (column) at a time.

Both SLIM articles stress an important point, which is that the regularization is needed to maintain the item-item similarity a sparse matrix. Numerically, the result will be a similarity containing numerous zero or almost zero values. By applying the top-k selection in each column we remove those zero or small valued similarities. 

The purpose is twofold: 
- To remove some noise and allow the model an extra hyperparameter.
- To never store the full item-item similarity in memory, which can be prohibitively large. 

If you look at the full experiments of the extended journal version you will see that the results for EASE_R and SLIM BPR algorithms, both based on item-item similarity, are sometimes missig due to the similarity matrix (represented as a dense numpy array) requiring in excess of 15 GB. 
This does not happen in SLIM ElasticNet since it is not needed to store the full similarity in memory because we learn its columns one at a time and select only the top-k values.

I hope I have been able to address your question.

**Comment by JaireYu** [comment]
Hi, thank you for replying so soon! 
You are quite right, I run the code(without selecting top K) on a large-scale dataset. It run out of my memory.
I will accept your suggestion and select top-k.
Thank you again!
