### ISSUE TITLE
Missing LastFMReader and YelpReader

### ISSUE THREAD

**Issue by chz816** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#4]
First of all, thank you for these amazing projects and the detailed repo! It helps a lot and motivates me to pursue my research.

I met one problem when I tries to run "run_KDD_18_MCRec.py". The problem is because of missing LastFMReader and YelpReader files.

`from Conferences.KDD.MCRec_our_interface.LastFM.LastFMReader import LastFMReader`
`from Conferences.KDD.MCRec_our_interface.Yelp.YelpReader import YelpReader`

I don't find these two files in the repo. Could you please give me some instructions on this problem? Thank you!

**Comment by MaurizioFD** [comment]
Hi,
I am glad you found our work useful!

Those import statements should be removed, the MCRec model requires the data to be preprocessed in a specific way and the code provided by the authors only contained the Movielens100k dataset and the relative MCRec hardcoded metapaths, due to this we could not run the experiments for the two other datasets.
I have committed an updated version removing those readers.

**Comment by chz816** [comment]
Thank you so much!  Problem solved. Happy new year!
