### ISSUE TITLE
How can I get some example recommendations from a recommender?

### ISSUE THREAD

**Issue by ThomasAger** [MaurizioFD/RecSys2019_DeepLearning_Evaluation#7]
Hi, I have been using this repo for a while now, thanks for your hard work.

I was just wondering if there is some existing way to obtain a list of recommendations for a single, "made-up" user, e.g. if I wanted to test some different inputs based on expert knowledge to see how the recommender behaves.

To be more specific, I want to get recommendations for a new user, who has N interactions, that the system has not seen yet.

Appreciated.

I am using the SLIM_ElasticNet in particular.

**Comment by MaurizioFD** [comment]
Thank you!

The answer is that you can, to an extent. 
If you use the set_URM_train(URM_new) of the BaseRecommender class you can replace the URM used for training with another URM which contains the new data. The two must have the same size so you can either replace existing users or provide a URM for training containing empty users, which will be filled in the new one.

After setting the new URM you should be able to use the recommend(.) method to generate the recommendations.

MultVAE requries to do what you are asking due to the evaluation methodology on "unseen users", at validation time the validation data is added to the train data and then removed once finished, you can see an example of it here:
https://github.com/MaurizioFD/RecSys2019_DeepLearning_Evaluation/blob/7f4089ede260aa7a6907b266ce9070743be82698/Conferences/WWW/MultiVAE_our_interface/EvaluatorUserSubsetWrapper.py#L32

I wanted to create a more complete and flexible way of providing new data but each type of model handles these things differently (item based are ok, user based need retraining, matrix factorization probably to estimate the latent factors again etc..) so I stopped there.

**Comment by ThomasAger** [comment]
Thank you so much. It worked great! 

I will copy-paste my code in case others may need it:

        # Create an instance of the recommender with the original data
        recommender_instance = recommender_class(URM_train)

        # Load the model
        recommender_instance.load_model(folder_path=folder_path, file_name=file_name)

        # Evaluate recommender and get results for the first cutoff
        result_dict, result_string = evaluator_test.evaluateRecommender(recommender_instance)
        
        # Create the replacement URM with new users to test
        URM_new = np.zeros(shape=URM_train.shape)
        
        # Based on the mapping provided in the MovieLens100K data, map movie names to ids
        URM_new[0][94] = 5.0
        URM_new[0][216] = 5.0
        URM_new[0][1098] = 5.0
        
        # Convert to CSR matrix
        URM_new = sp.csr_matrix(URM_new)
        
        # Change URM to new users
        recommender_instance.set_URM_train(URM_new)

        # Get recommendations
        recommended_items_batch_list = recommender_instance.recommend(0)
        
        # Print IDs
        print(recommended_items_batch_list)
